#!/usr/bin/env bash
#
# Rename this template to a real project.
#
# Replaces the template name everywhere it appears — package.json,
# docker-compose.yml, documentation, issue templates — writes a .env.local with
# the app's data-layer configuration, and optionally resets git history so the
# new project starts from a single clean commit.
#
# The new name becomes the APP SLUG: one name for the Cloud Run service, the
# runtime service account, the Firestore database and the Cloud Storage bucket.
# That is what keeps two apps in one GCP project from reaching each other's data.
#
# Usage:
#   ./scripts/rename-project.sh my-app
#   ./scripts/rename-project.sh my-app --owner acme --project my-gcp-project
#   ./scripts/rename-project.sh my-app --owner acme --reset-git
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

OLD_NAME="nextjs-cloudrun-template"
OLD_OWNER="thesandx"

if [[ -t 1 ]]; then
  BOLD_WARN=$'\033[1;33m'; RESET_WARN=$'\033[0m'
else
  BOLD_WARN=''; RESET_WARN=''
fi

NEW_NAME=""
NEW_OWNER=""
GCP_PROJECT=""
GCP_REGION="asia-south1"
RESET_GIT="false"

USAGE="Usage: $0 <new-name> [--owner <github-owner>] [--project <gcp-project>] [--region <region>] [--reset-git]"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --owner)     NEW_OWNER="${2:-}"; shift 2 ;;
    --project)   GCP_PROJECT="${2:-}"; shift 2 ;;
    --region)    GCP_REGION="${2:-}"; shift 2 ;;
    --reset-git) RESET_GIT="true"; shift ;;
    -h|--help)   echo "$USAGE"; exit 0 ;;
    -*)          echo "Unknown option: $1" >&2; exit 1 ;;
    *)           NEW_NAME="$1"; shift ;;
  esac
done

if [[ -z "$NEW_NAME" ]]; then
  echo "$USAGE" >&2
  exit 1
fi

# npm package names: lowercase, alphanumeric, hyphens. Also a valid Cloud Run
# service name, which has the same constraints plus a 49-character limit.
if ! [[ "$NEW_NAME" =~ ^[a-z][a-z0-9-]{0,48}$ ]]; then
  echo "Invalid name: '${NEW_NAME}'" >&2
  echo "Must start with a letter and contain only lowercase letters, digits" >&2
  echo "and hyphens (max 49 chars) to be valid for both npm and Cloud Run." >&2
  exit 1
fi

echo "Renaming '${OLD_NAME}' to '${NEW_NAME}'"
[[ -n "$NEW_OWNER" ]] && echo "Renaming owner '${OLD_OWNER}' to '${NEW_OWNER}'"
echo

# Everything tracked by git, excluding this script (which contains the literals
# it is searching for) and the lockfile.
mapfile -t FILES < <(git ls-files | grep -v '^scripts/rename-project.sh$' | grep -v '^pnpm-lock.yaml$')

replace_in_files() {
  local from="$1" to="$2" count=0
  for file in "${FILES[@]}"; do
    [[ -f "$file" ]] || continue
    if grep -q "$from" "$file" 2>/dev/null; then
      # macOS sed needs an explicit empty suffix for -i; GNU sed does not.
      if sed --version >/dev/null 2>&1; then
        sed -i "s|${from}|${to}|g" "$file"
      else
        sed -i '' "s|${from}|${to}|g" "$file"
      fi
      echo "  ${file}"
      count=$((count + 1))
    fi
  done
  echo "  → ${count} file(s) updated"
}

echo "Replacing project name:"
replace_in_files "$OLD_NAME" "$NEW_NAME"

if [[ -n "$NEW_OWNER" ]]; then
  echo
  echo "Replacing owner:"
  replace_in_files "$OLD_OWNER" "$NEW_OWNER"
fi

# ---------------------------------------------------------------------------
# .env.local — the app's data-layer configuration
#
# APP_SLUG is required in production and validated at container start, so it has
# to be set somewhere before the first deploy. Writing it here means the very
# first `pnpm dev` works, and the deploy workflow derives the same names from
# the same slug.
#
# Never overwritten: a .env.local that already exists holds values somebody
# chose, and those matter more than these defaults.
# ---------------------------------------------------------------------------
echo
echo "Local configuration:"

if [[ -f .env.local ]]; then
  echo "  · .env.local exists; leaving it alone"
  echo "    Add these by hand if they are missing:"
  echo "      APP_SLUG=${NEW_NAME}"
  echo "      FIRESTORE_DATABASE_ID=${NEW_NAME}-db"
else
  {
    echo "# Local development configuration for ${NEW_NAME}."
    echo "# Generated by scripts/rename-project.sh. Gitignored — never commit it."
    echo "# Every variable here is documented in .env.example."
    echo
    echo "LOG_LEVEL=debug"
    echo
    echo "NEXT_PUBLIC_APP_NAME=${NEW_NAME}"
    echo "NEXT_PUBLIC_APP_URL=http://localhost:3000"
    echo
    echo "APP_SLUG=${NEW_NAME}"
    echo "GCP_REGION=${GCP_REGION}"

    if [[ -n "$GCP_PROJECT" ]]; then
      echo "GCP_PROJECT_ID=${GCP_PROJECT}"
      echo
      echo "# Defaults to <APP_SLUG>-db; stated here so it is visible."
      echo "FIRESTORE_DATABASE_ID=${NEW_NAME}-db"
      echo
      echo "# The DEV bucket, not production. A laptop must never write to the"
      echo "# production bucket. scripts/gcp-bootstrap.sh creates both."
      echo "GCS_BUCKET=${GCP_PROJECT}-${NEW_NAME}-media-dev"
    else
      echo
      echo "# Fill these in after running scripts/gcp-bootstrap.sh."
      echo "# The app starts without them locally and fails fast in production."
      echo "GCP_PROJECT_ID="
      echo "FIRESTORE_DATABASE_ID=${NEW_NAME}-db"
      echo "# Point at the DEV bucket, never production: <project>-${NEW_NAME}-media-dev"
      echo "GCS_BUCKET="
    fi

    echo
    echo "# Uncomment to run against the local emulator instead of real"
    echo "# Firestore. Start it with: pnpm db:emulator"
    echo "# FIRESTORE_EMULATOR_HOST=127.0.0.1:8085"
  } > .env.local
  echo "  → wrote .env.local"
fi

if [[ "$RESET_GIT" == "true" ]]; then
  echo
  read -r -p "Delete all git history and start fresh? [y/N] " reply
  if [[ "$reply" =~ ^[Yy]$ ]]; then
    rm -rf .git
    git init --quiet
    git add -A
    git commit --quiet -m "Initial commit from nextjs-cloudrun-template"
    echo "  → history reset to a single commit"
  else
    echo "  → skipped"
  fi
fi

cat <<EOF

Done. Next steps:

  1. pnpm install
  2. Update the description in package.json
  3. Update the title and overview in README.md
  4. Set the real team handle in .github/CODEOWNERS
  5. ./scripts/gcp-bootstrap.sh \\
       --project ${GCP_PROJECT:-<gcp-project>} \\
       --region ${GCP_REGION} \\
       --repo ${NEW_OWNER:-<owner>}/${NEW_NAME} \\
       --service ${NEW_NAME}

     Creates the Firestore database ${NEW_NAME}-db and the bucket, both in
     ${GCP_REGION}. ${BOLD_WARN}Both locations are permanent.${RESET_WARN}

  6. Check .env.local, then: pnpm dev

  The example at /example shows the data layer end to end. Delete it once you
  have copied the pattern — see services/example.service.ts.

EOF
